#!/bin/sh

sox  sine_mono.wav  -b  16  -e  floating-point    --endian  big     sine_mono_16fp_be.aiff
sox  sine_mono.wav  -b  16  -e  floating-point    --endian  big     sine_mono_16fp_be.au
sox  sine_mono.wav  -b  16  -e  floating-point    --endian  big     sine_mono_16fp_be.wav
sox  sine_mono.wav  -b  16  -e  floating-point    --endian  little  sine_mono_16fp_le.aiff
sox  sine_mono.wav  -b  16  -e  floating-point    --endian  little  sine_mono_16fp_le.au
sox  sine_mono.wav  -b  16  -e  floating-point    --endian  little  sine_mono_16fp_le.wav
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  big     sine_mono_16s_be.aiff
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  big     sine_mono_16s_be.au
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  big     sine_mono_16s_be.wav
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  little  sine_mono_16s_le.aiff
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  little  sine_mono_16s_le.au
sox  sine_mono.wav  -b  16  -e  signed-integer    --endian  little  sine_mono_16s_le.wav
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  big     sine_mono_16u_be.aiff
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  big     sine_mono_16u_be.au
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  big     sine_mono_16u_be.wav
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  little  sine_mono_16u_le.aiff
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  little  sine_mono_16u_le.au
sox  sine_mono.wav  -b  16  -e  unsigned-integer  --endian  little  sine_mono_16u_le.wav
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  big     sine_mono_24fp_be.aiff
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  big     sine_mono_24fp_be.au
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  big     sine_mono_24fp_be.wav
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  little  sine_mono_24fp_le.aiff
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  little  sine_mono_24fp_le.au
sox  sine_mono.wav  -b  24  -e  floating-point    --endian  little  sine_mono_24fp_le.wav
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  big     sine_mono_24s_be.aiff
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  big     sine_mono_24s_be.au
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  big     sine_mono_24s_be.wav
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  little  sine_mono_24s_le.aiff
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  little  sine_mono_24s_le.au
sox  sine_mono.wav  -b  24  -e  signed-integer    --endian  little  sine_mono_24s_le.wav
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  big     sine_mono_24u_be.aiff
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  big     sine_mono_24u_be.au
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  big     sine_mono_24u_be.wav
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  little  sine_mono_24u_le.aiff
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  little  sine_mono_24u_le.au
sox  sine_mono.wav  -b  24  -e  unsigned-integer  --endian  little  sine_mono_24u_le.wav
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  big     sine_mono_32fp_be.aiff
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  big     sine_mono_32fp_be.au
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  big     sine_mono_32fp_be.wav
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  little  sine_mono_32fp_le.aiff
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  little  sine_mono_32fp_le.au
sox  sine_mono.wav  -b  32  -e  floating-point    --endian  little  sine_mono_32fp_le.wav
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  big     sine_mono_32s_be.aiff
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  big     sine_mono_32s_be.au
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  big     sine_mono_32s_be.wav
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  little  sine_mono_32s_le.aiff
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  little  sine_mono_32s_le.au
sox  sine_mono.wav  -b  32  -e  signed-integer    --endian  little  sine_mono_32s_le.wav
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  big     sine_mono_32u_be.aiff
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  big     sine_mono_32u_be.au
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  big     sine_mono_32u_be.wav
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  little  sine_mono_32u_le.aiff
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  little  sine_mono_32u_le.au
sox  sine_mono.wav  -b  32  -e  unsigned-integer  --endian  little  sine_mono_32u_le.wav
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  big     sine_mono_8fp_be.aiff
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  big     sine_mono_8fp_be.au
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  big     sine_mono_8fp_be.wav
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  little  sine_mono_8fp_le.aiff
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  little  sine_mono_8fp_le.au
sox  sine_mono.wav  -b  8   -e  floating-point    --endian  little  sine_mono_8fp_le.wav
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  big     sine_mono_8s_be.aiff
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  big     sine_mono_8s_be.au
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  big     sine_mono_8s_be.wav
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  little  sine_mono_8s_le.aiff
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  little  sine_mono_8s_le.au
sox  sine_mono.wav  -b  8   -e  signed-integer    --endian  little  sine_mono_8s_le.wav
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  big     sine_mono_8u_be.aiff
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  big     sine_mono_8u_be.au
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  big     sine_mono_8u_be.wav
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  little  sine_mono_8u_le.aiff
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  little  sine_mono_8u_le.au
sox  sine_mono.wav  -b  8   -e  unsigned-integer  --endian  little  sine_mono_8u_le.wav

sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  big     sine_stereo_16fp_be.aiff
sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  big     sine_stereo_16fp_be.au
sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  big     sine_stereo_16fp_be.wav
sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  little  sine_stereo_16fp_le.aiff
sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  little  sine_stereo_16fp_le.au
sox  sine_stereo.wav  -b  16  -e  floating-point    --endian  little  sine_stereo_16fp_le.wav
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  big     sine_stereo_16s_be.aiff
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  big     sine_stereo_16s_be.au
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  big     sine_stereo_16s_be.wav
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  little  sine_stereo_16s_le.aiff
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  little  sine_stereo_16s_le.au
sox  sine_stereo.wav  -b  16  -e  signed-integer    --endian  little  sine_stereo_16s_le.wav
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  big     sine_stereo_16u_be.aiff
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  big     sine_stereo_16u_be.au
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  big     sine_stereo_16u_be.wav
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  little  sine_stereo_16u_le.aiff
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  little  sine_stereo_16u_le.au
sox  sine_stereo.wav  -b  16  -e  unsigned-integer  --endian  little  sine_stereo_16u_le.wav
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  big     sine_stereo_24fp_be.aiff
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  big     sine_stereo_24fp_be.au
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  big     sine_stereo_24fp_be.wav
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  little  sine_stereo_24fp_le.aiff
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  little  sine_stereo_24fp_le.au
sox  sine_stereo.wav  -b  24  -e  floating-point    --endian  little  sine_stereo_24fp_le.wav
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  big     sine_stereo_24s_be.aiff
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  big     sine_stereo_24s_be.au
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  big     sine_stereo_24s_be.wav
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  little  sine_stereo_24s_le.aiff
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  little  sine_stereo_24s_le.au
sox  sine_stereo.wav  -b  24  -e  signed-integer    --endian  little  sine_stereo_24s_le.wav
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  big     sine_stereo_24u_be.aiff
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  big     sine_stereo_24u_be.au
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  big     sine_stereo_24u_be.wav
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  little  sine_stereo_24u_le.aiff
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  little  sine_stereo_24u_le.au
sox  sine_stereo.wav  -b  24  -e  unsigned-integer  --endian  little  sine_stereo_24u_le.wav
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  big     sine_stereo_32fp_be.aiff
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  big     sine_stereo_32fp_be.au
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  big     sine_stereo_32fp_be.wav
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  little  sine_stereo_32fp_le.aiff
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  little  sine_stereo_32fp_le.au
sox  sine_stereo.wav  -b  32  -e  floating-point    --endian  little  sine_stereo_32fp_le.wav
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  big     sine_stereo_32s_be.aiff
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  big     sine_stereo_32s_be.au
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  big     sine_stereo_32s_be.wav
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  little  sine_stereo_32s_le.aiff
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  little  sine_stereo_32s_le.au
sox  sine_stereo.wav  -b  32  -e  signed-integer    --endian  little  sine_stereo_32s_le.wav
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  big     sine_stereo_32u_be.aiff
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  big     sine_stereo_32u_be.au
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  big     sine_stereo_32u_be.wav
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  little  sine_stereo_32u_le.aiff
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  little  sine_stereo_32u_le.au
sox  sine_stereo.wav  -b  32  -e  unsigned-integer  --endian  little  sine_stereo_32u_le.wav
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  big     sine_stereo_8fp_be.aiff
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  big     sine_stereo_8fp_be.au
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  big     sine_stereo_8fp_be.wav
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  little  sine_stereo_8fp_le.aiff
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  little  sine_stereo_8fp_le.au
sox  sine_stereo.wav  -b  8   -e  floating-point    --endian  little  sine_stereo_8fp_le.wav
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  big     sine_stereo_8s_be.aiff
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  big     sine_stereo_8s_be.au
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  big     sine_stereo_8s_be.wav
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  little  sine_stereo_8s_le.aiff
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  little  sine_stereo_8s_le.au
sox  sine_stereo.wav  -b  8   -e  signed-integer    --endian  little  sine_stereo_8s_le.wav
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  big     sine_stereo_8u_be.aiff
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  big     sine_stereo_8u_be.au
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  big     sine_stereo_8u_be.wav
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  little  sine_stereo_8u_le.aiff
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  little  sine_stereo_8u_le.au
sox  sine_stereo.wav  -b  8   -e  unsigned-integer  --endian  little  sine_stereo_8u_le.wav

ls sine_stereo* | tee > stereos.txt
ls sine_mono* | tee > monos.txt

